# Generated by Django 2.2.3 on 2019-07-30 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bug',
            options={'verbose_name': 'bug 管理', 'verbose_name_plural': 'bug 管理'},
        ),
    ]
